.TH "ship.Processor.Compiler.Assembler" 3 "Ship Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ship.Processor.Compiler.Assembler
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBReset\fP ()"
.br
.ti -1c
.RI "bool \fBParse\fP (string[] input)"
.br
.ti -1c
.RI "void \fBAssemble\fP (MemoryStream output)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly List< OpcodeDecl > \fBOpcodes\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "List< ErrorDecl > \fBErrors\fP = []\fR [get]\fP"
.br
.ti -1c
.RI "ushort \fBProgramSize\fP\fR [get, set]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Ship Processor from the source code\&.
