.TH "ship.Processor.Compiler.Passes.IAsmPass" 3 "Ship Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ship.Processor.Compiler.Passes.IAsmPass
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBship\&.Processor\&.Compiler\&.Passes\&.AssemblePass\fP, and \fBship\&.Processor\&.Compiler\&.Passes\&.CollectLabelsPass\fP\&.
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBAssembler\fP \fBParent\fP = null!"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Ship Processor from the source code\&.
