.TH "ship.Processor.Compiler.Parser" 3 "Ship Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ship.Processor.Compiler.Parser
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "OperationDecl[] \fBScanFile\fP (string[] lines)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Ship Processor from the source code\&.
