.TH "ship.Processor.Compiler.Passes.CollectLabelsPass" 3 "Ship Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ship.Processor.Compiler.Passes.CollectLabelsPass
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBship\&.Processor\&.Compiler\&.Passes\&.IAsmPass\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCollectLabelsPass\fP (\fBAssembler\fP parent)"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBship\&.Processor\&.Compiler\&.Passes\&.IAsmPass\fP
.in +1c
.ti -1c
.RI "\fBAssembler\fP \fBParent\fP = null!"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Ship Processor from the source code\&.
